spring:
  datasource:
    generate-unique-name: false # the jdbc url will be default jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
logging:
  level:
    org.springframework.web: TRACE

